'use strict'

var dbm
var type
var seed

/**
 * We receive the dbmigrate dependency from dbmigrate initially.
 * This enables us to not have to rely on NODE_PATH.
 */
exports.setup = function (options, seedLink) {
    dbm = options.dbmigrate
    type = dbm.dataType
    seed = seedLink
}

exports.up = function (db) {
    return db.runSql(`
  
    CREATE TABLE public.likes (
        id integer primary key generated by default as identity,
        user_id int NOT NULL,
        review_id int NOT NULL,
        created_at timestamp NOT NULL DEFAULT NOW(),
        updated_at timestamp NOT NULL DEFAULT NOW(),
        resource_id varchar(10485760) NOT NULL,
        CONSTRAINT likes_resource_id_uq UNIQUE (resource_id),
        CONSTRAINT likes_user_id_fk FOREIGN KEY (user_id) REFERENCES public.users(id),
        CONSTRAINT likes_review_id_fk FOREIGN KEY (review_id) REFERENCES public.reviews(id),
        CONSTRAINT likes_user_id_review_id_uq UNIQUE (user_id, review_id)

    );
    
    CREATE TABLE public.follows (
        id integer primary key generated by default as identity,
        from_user_id int NOT NULL,
        to_user_id int NOT NULL,
        created_at timestamp NOT NULL DEFAULT NOW(),
        updated_at timestamp NOT NULL DEFAULT NOW(),
        resource_id varchar(10485760) NOT NULL,
        CONSTRAINT follows_resource_id_uq UNIQUE (resource_id),
        CONSTRAINT follows_from_user_id_fk FOREIGN KEY (from_user_id) REFERENCES public.users(id),
        CONSTRAINT follows_to_user_id_fk FOREIGN KEY (to_user_id) REFERENCES public.users(id),
        CONSTRAINT follows_from_user_id_to_user_id_uq UNIQUE (from_user_id, to_user_id)

    );
    
    ALTER TABLE users
        ADD COLUMN location varchar(10485760) null;
    `)
}

exports.down = function (db) {
    return null
}

exports._meta = {
    version: 1
}
