/* Replace with your SQL commands */
CREATE TABLE public."users" (
  id integer primary key generated by default as identity,
  email varchar(10485760) NOT NULL,
  "password" varchar(10485760) NOT NULL,
  first_name varchar(10485760) NULL,
  last_name varchar(10485760) NULL,
  phone varchar(10485760) NULL,
  created_at timestamp NOT NULL DEFAULT NOW(),
  updated_at timestamp NOT NULL DEFAULT NOW(),
  resource_id varchar(10485760) NOT NULL,
  CONSTRAINT users_resource_id_uq UNIQUE (resource_id),
  CONSTRAINT users_phone_uq UNIQUE (phone),
  CONSTRAINT users_email_uq UNIQUE (email)
);

CREATE TABLE public."roles" (
  id integer primary key generated by default as identity,
  name varchar(10485760) NOT NULL,
  created_at timestamp NOT NULL DEFAULT NOW(),
  updated_at timestamp NOT NULL DEFAULT NOW(),
  resource_id varchar(10485760) NOT NULL,
  CONSTRAINT roles_resource_id_uq UNIQUE (resource_id),
  CONSTRAINT roles_name_uq UNIQUE (name)
);

CREATE TABLE public.user_has_roles (
  id integer primary key generated by default as identity,
  user_id int NOT NULL,
  role_id int NOT NULL,
  created_at timestamp NOT NULL DEFAULT NOW(),
  updated_at timestamp NOT NULL DEFAULT NOW(),
  resource_id varchar(10485760) NOT NULL,
  CONSTRAINT user_has_roles_resource_id_uq UNIQUE (resource_id),
  CONSTRAINT user_has_roles_user_id_role_id_uq UNIQUE (user_id, role_id),
  CONSTRAINT user_has_roles_user_id_fk FOREIGN KEY (user_id) REFERENCES public.users(id),
  CONSTRAINT user_has_roles_role_id_fk FOREIGN KEY (role_id) REFERENCES public.roles(id)
);

CREATE TABLE public.places (
  id integer primary key generated by default as identity,
  name varchar(10485760) NOT NULL,
  google_place_id varchar(10485760),
  created_at timestamp NOT NULL DEFAULT NOW(),
  updated_at timestamp NOT NULL DEFAULT NOW(),
  resource_id varchar(10485760) NOT NULL,
  CONSTRAINT places_resource_id_uq UNIQUE (resource_id),
  CONSTRAINT places_name_uq UNIQUE (name),
  CONSTRAINT places_google_place_id_uq UNIQUE (google_place_id)
);

CREATE TABLE public.reviews (
  id integer primary key generated by default as identity,
  user_id int NOT NULL,
  place_id int NOT NULL,
  rating int NOT NULL,
  comment varchar(10485760) NOT NULL,
  created_at timestamp NOT NULL DEFAULT NOW(),
  updated_at timestamp NOT NULL DEFAULT NOW(),
  resource_id varchar(10485760) NOT NULL,
  CONSTRAINT reviews_resource_id_uq UNIQUE (resource_id),
  CONSTRAINT reviews_user_id_place_id_uq UNIQUE (user_id, place_id),
  CONSTRAINT reviews_user_id_fk FOREIGN KEY (user_id) REFERENCES public.users(id),
  CONSTRAINT reviews_place_id_fk FOREIGN KEY (place_id) REFERENCES public.places(id)
);

CREATE TABLE public.photos (
  id integer primary key generated by default as identity,
  url int NOT NULL,
  created_at timestamp NOT NULL DEFAULT NOW(),
  updated_at timestamp NOT NULL DEFAULT NOW(),
  resource_id varchar(10485760) NOT NULL,
  CONSTRAINT photos_resource_id_uq UNIQUE (resource_id),
  CONSTRAINT photos_url_uq UNIQUE (url)
);

CREATE TABLE public.review_has_photos (
  id integer primary key generated by default as identity,
  review_id int NOT NULL,
  photo_id int NOT NULL,
  created_at timestamp NOT NULL DEFAULT NOW(),
  updated_at timestamp NOT NULL DEFAULT NOW(),
  resource_id varchar(10485760) NOT NULL,
  CONSTRAINT review_has_photos_resource_id_uq UNIQUE (resource_id),
  CONSTRAINT review_has_photos_review_id_photo_id_uq UNIQUE (review_id, photo_id),
  CONSTRAINT review_has_photos_review_id_fk FOREIGN KEY (review_id) REFERENCES public.reviews(id),
  CONSTRAINT review_has_photos_photo_id_fk FOREIGN KEY (photo_id) REFERENCES public.photos(id)
);

CREATE TABLE public.clubs (
  id integer primary key generated by default as identity,
  name varchar(10485760) NOT NULL,
  photo_id int NOT NULL,
  created_at timestamp NOT NULL DEFAULT NOW(),
  updated_at timestamp NOT NULL DEFAULT NOW(),
  resource_id varchar(10485760) NOT NULL,
  CONSTRAINT clubs_resource_id_uq UNIQUE (resource_id),
  CONSTRAINT clubs_name_uq UNIQUE (name),
  CONSTRAINT clubs_photo_id_fk FOREIGN KEY (photo_id) REFERENCES public.photos(id)
);

CREATE TABLE public.club_has_users (
  id integer primary key generated by default as identity,
  club_id int NOT NULL,
  user_id int NOT NULL,
  is_admin boolean NOT NULL,
  created_at timestamp NOT NULL DEFAULT NOW(),
  updated_at timestamp NOT NULL DEFAULT NOW(),
  resource_id varchar(10485760) NOT NULL,
  CONSTRAINT club_has_users_resource_id_uq UNIQUE (resource_id),
  CONSTRAINT club_has_users_club_id_user_id_uq UNIQUE (club_id, user_id),
  CONSTRAINT club_has_users_club_id_fk FOREIGN KEY (club_id) REFERENCES public.clubs(id),
  CONSTRAINT club_has_users_user_id_fk FOREIGN KEY (user_id) REFERENCES public.users(id)
);