
name: Build and Deploy

on: push

jobs:
    backend:
        name: Backend
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repo
              uses: actions/checkout@master

            - name: npm i -> backend
              run: npm install

            - name: run npm deploy
              run: AWS_SECRET_ACCESS_KEY=${{secrets.AWS_SECRET_ACCESS_KEY}} AWS_ACCESS_KEY_ID=${{secrets.AWS_ACCESS_KEY_ID}} npm run deploy